namespace FEZRepacker.Core.Definitions.Game.TrackedSong
{
    [XnbType("FezEngine.Structure.ShardNotes")]
    public enum ShardNotes
    {
        C2,
        Csharp2,
        D2,
        Dsharp2,
        E2,
        F2,
        Fsharp2,
        G2,
        Gsharp2,
        A2,
        Asharp2,
        B2,
        C3,
        Csharp3,
        D3,
        Dsharp3,
        E3,
        F3,
        Fsharp3,
        G3,
        Gsharp3,
        A3,
        Asharp3,
        B3,
        C4
    }
}
