name: Core CD

on:
  push:
    tags: 
    - '*'

jobs:
  release-nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore packages
        run: dotnet restore Core/FEZRepacker.Core.csproj

      - name: Build
        run: dotnet build Core/FEZRepacker.Core.csproj -c Release

      - name: Pack
        run: dotnet pack Core/FEZRepacker.Core.csproj -c Release --no-build --output .

      - name: Push
        run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
