name: Interface CD

on:
  push:
    tags: '*'

jobs:
  build-interface:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.x'

      - name: Restore packages
        run: dotnet restore Interface/FEZRepacker.Interface.csproj

      - name: Build for Windows
        run: dotnet publish Interface/FEZRepacker.Interface.csproj -c Release -r win-x86 --self-contained

      - name: Build for Linux
        run: dotnet publish Interface/FEZRepacker.Interface.csproj -c Release -r linux-arm64 --self-contained

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: FEZRepacker.Interface.Windows
          path: Interface/bin/Release/net6.0/win-x86/publish/FEZRepacker.Interface.exe
          if-no-files-found: error

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: FEZRepacker.Interface.Linux
          path: Interface/bin/Release/net6.0/linux-arm64/publish/FEZRepacker.Interface
          if-no-files-found: error
  release:
    if: github.repository == 'FEZModding/FEZRepacker'
    needs: [build-interface]
    runs-on: ubuntu-latest
    steps:

      - name: Download Linux Build
        uses: actions/download-artifact@v4
        with:
          name: FEZRepacker.Interface.Linux
      - name: Rename Linux Build
        run: mv FEZRepacker.Interface FEZRepacker

      - name: Download Windows Build
        uses: actions/download-artifact@v4
        with:
          name: FEZRepacker.Interface.Windows
      - name: Rename Windows Build
        run: mv FEZRepacker.Interface.exe FEZRepacker.exe

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ## Usage

            Download one of the following:

            - `FEZRepacker.exe` - Windows standalone command-line interface
            - `FEZRepacker` - Linux standalone command-line interface

            ...and consult the README.md for usage details.

            Additionally, Core library can be accessed as a NuGet package: https://www.nuget.org/packages/FEZRepacker.Core

            ## Changelog

            TODO
          files: |
            FEZRepacker.exe
            FEZRepacker
          fail_on_unmatched_files: true
